
[build]
  command = "echo 'No build command'"
  publish = "."
  functions = "functions"  # Προσθήκη κενού φακέλου functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Απενεργοποίηση plugins
[plugins]
  package = "netlify-plugin-inline-functions-env"
  enabled = false
  command = "echo 'No build command'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
